spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ust_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true